default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USER'] || 'user' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'x_paste_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'x_paste_test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

