default: &default
  errbit_project_key: <%= ENV['ERRBIT_PROJECT_KEY'] %>

development:
  <<: *default
  secret_key_base: 9ac2d0ad8ebcc312090e99d745006d3cf8

test:
  <<: *default
  secret_key_base: a1580ad61ccb6ac60f9f256948cf63d6e20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
