AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  Include:
    - app/views/**/*.axlsx
  Exclude:
    - db/schema.rb
    - spec/

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/LineLength:
  Enabled: false