# This is a YAML-formatted file.

image: registry.slurm.io/slurm3/xpaste
imageTag: master.1
imagePullSecret: xpaste-gitlab-registry

env:
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: 1
  DB_HOST: postgresql-postgresql
  DB_PORT: 5432
  DB_NAME: xpaste

# This variables is taken from secret
# Value is secret name where variable value can be found
# Key in secret equals lowercased variable name with "_" replaced by "-"
# The secret should be created manually
envSecret:
  SECRET_KEY_BASE: slurm3-xpaste
  DB_USER: slurm3-xpaste
  DB_PASSWORD: slurm3-xpaste

# Resources for app. Limits is the maximum number of resources that app cas use.
# And requests is resources that will be granted to the app at start time.
replicas: 2

app:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

service:
  port: 80

ingress:
  host: xpaste.s<номер своего логина>.slurm.io
